#!/bin/bash
echo "🔧 SUPABASE CREDENTIAL UPDATER"
echo "=============================="
echo ""
echo "Your current .env.local has these Supabase lines:"
grep SUPABASE .env.local
echo ""
echo "These are PLACEHOLDER values - that's why you're in guest mode!"
echo ""
echo "To fix this, you need to:"
echo "1. Go to https://supabase.com"
echo "2. Open your project"
echo "3. Go to Settings → API"
echo "4. Copy the 3 values and replace them manually in .env.local"
echo ""
echo "Expected format:"
echo "NEXT_PUBLIC_SUPABASE_URL=https://abcdefgh.supabase.co"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
